FROM balenalib/%%BALENA_MACHINE_NAME%%-node:10

COPY package.json package.json

RUN npm install 
RUN npm install @iota/core 
RUN npm install @iota/converter 
RUN npm install @iota/extract-json

WORKDIR /usr/src/app

RUN JOBS=MAX npm install --production --unsafe-perm && npm cache verify && rm -rf /tmp/*

COPY . ./

ENV UDEV=1

CMD ["node", "iota-random-payment.js"]